/////////////////////////////////////////////////////////////////////////////////////////////////////
// Unit tests using the doctest framework.
//
// This file serves as a placeholder for main(), which is generated by doctest.
//
// See the documentation section for an overview: https://github.com/onqtam/doctest#documentation
//
// Running with filtering of CATCH2 flags:
//
//    > sudo ./obj/qpu-debug/bin/runTests -tc=*[ops]*,*[dft]*    // all tests matching at least one tag
//    > sudo ./obj/qpu-debug/bin/runTests -tce=*[matrix]*        // Exclude all tags in list
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest.h"
