// DO NOT EDIT - this file is automatically generated by merge_driinfo.py

/*
Use as:

#include "driconf.h"

static const char driinfo_xml[] =
#include "this_file"
;
*/

DRI_CONF_BEGIN
   DRI_CONF_SECTION_MISCELLANEOUS
      DRI_CONF_V3D_NONMSAA_TEXTURE_SIZE_LIMIT("false")
   DRI_CONF_SECTION_END
DRI_CONF_END
